### ISSUE TITLE
Rapportera eventuella fel när openapi spec skall läsas in för funktionen utforska API

### ISSUE THREAD

**Issue by istyf** [DIGGSweden/dataportal-web#18]
Det verkar ha skett en förändring i beteendet när en Distribution pekar ut en API-spec med hjälp av conformsTo.

Jag har tidigare haft möjlighet att utforska API:et https://www.dataportal.se/sv/datasets/61_2071/oppna-data-fran-sundsvalls-kommun , men nu fungerar det plötsligt inte längre utan att jag kan koppla det till någon förändring på min sida.

Jag har försökt ett flertal olika tricks så som att generera om rdf med diggs dcat-ap-processor, ändra OpenAPI-version, med mera, men inget vill fungera.

Jag gissar att det är någon validering eller något som går fel någonstans, alternativt att swaggerui får problem med något i openapi-specen, men det ges inget felmeddelande någonstans. Skulle detta kunna vara en del av valideringen så att det går att få ett tydligare felmeddelande om varför utforska-funktionen lyser med sin frånvaro?

**Comment by istyf** [comment]
Någon av mina sista ändringar av rdf verkar ha löst problemet, för nu dyker "utforska" upp i dataportalen. Men den gjorde inte det i sandbox utan först efter en ny sköljning till produktionsmiljön.

Hur som helst så kvarstår önskemålet om någon möjlighet till bättre diagnostisering när det inte funkar.

**Comment by danfun-kit** [comment]
Det är ett separat nattjobb hos Metasolutions som markerar vilka datamängder som har openapi-specifikation. Därmed blir det som längst en dags delay tills dataportal.se kan plocka upp detta. Diagnostisering av detta därmed i backend och kan för tillfället inte visas i realtid.
