### ISSUE TITLE
Skiftlägeskänslig sökning

### ISSUE THREAD

**Issue by weipe** [DIGGSweden/dataportal-web#21]
Tror det vore bra om sökmotorn inte var skiftlägeskänslig.

Vi laddade upp ett dataset med titeln "Faktablad", och söker man på "faktablad" så får man ingen träff (måste ange "Faktablad" som sökterm).

**Comment by jonassodergren** [comment]
Märkligt, fungerar för mig i chrome.

**Comment by danfun-kit** [comment]
Den är inte skifteskänslig, kan ha vart ett övergående problem innan datamängderna hunnit skördats.
