### ISSUE TITLE
Problem med visningar i Safari

### ISSUE THREAD

**Issue by jonassodergren** [DIGGSweden/dataportal-web#22]
Har inte gjort några avancerade tester. Men dataportalen fungerar inte alls i safari för mig. När man klickar på ett dataset så visas ingen information. (fungerar i chrome etc)

**Comment by danfun-kit** [comment]
Det gjordes en deploy den 19:e, vilket kan leda till kortare nertider av dataportal.se, det berodde mest troligt på detta. Men vi ser över deployrutinerna för att minska risken för nertid.

**Comment by jonassodergren** [comment]
Har ni verifierat att dataportal.se fungerar i safari på mac? För mig fungerar inte sajten fortfarande. (Men fungerar bra i chrome)

**Comment by danfun-kit** [comment]
Självklart, det är en del i testkedjan. Skulle du kunna skicka lite mer detaljerad om detta? Vi skulle gärna vilja veta mac-version, safari-version, skärmdump, vilken http-status-kod du får, om det finns några fel i consolen.

**Comment by jonassodergren** [comment]
Error loggen från safari
----------------------

[Error] The source list for Content Security Policy directive 'script-src' contains an invalid source: ''strict-dynamic''. It will be ignored.
[Error] Unrecognized Content-Security-Policy directive 'prefetch-src'.

[Error] Unrecognized Content-Security-Policy directive 'style-src-elem'.

[Error] Unrecognized Content-Security-Policy directive 'style-src-attr'.

[Error] <link rel=preload> has an invalid `imagesrcset` value (www.dataportal.se, line 1)
[Error] <link rel=preload> has an invalid `imagesrcset` value (www.dataportal.se, line 1)
[Error] <link rel=preload> has an invalid `imagesrcset` value (www.dataportal.se, line 1)
[Error] <link rel=preload> has an invalid `imagesrcset` value (www.dataportal.se, line 1)
[Error] The source list for Content Security Policy directive 'script-src' contains an invalid source: ''strict-dynamic''. It will be ignored.
[Error] Unrecognized Content-Security-Policy directive 'prefetch-src'.

[Error] Unrecognized Content-Security-Policy directive 'style-src-elem'.

[Error] Unrecognized Content-Security-Policy directive 'style-src-attr'.

---------------
Mac 12.2.1 och Safari 15.3

**Comment by danfun-kit** [comment]
Tack! Vi kollar på det.

**Comment by danfun-kit** [comment]
Vi har deployat en tillfällig testversion till följande adress: https://dataportal-ndp568.kexnorr.se/sv
Har du möjlighet att testa om den adressen fungerar för dig? Får du samma fel där?

**Comment by jonassodergren** [comment]
Tack, verkar bli samma fel igen.

```
[Error] The source list for Content Security Policy directive 'script-src' contains an invalid source: ''strict-dynamic''. It will be ignored.
[Error] Unrecognized Content-Security-Policy directive 'prefetch-src'.

[Error] Unrecognized Content-Security-Policy directive 'style-src-elem'.

[Error] Unrecognized Content-Security-Policy directive 'style-src-attr'.

[Error] Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy. (api-for-kvalifikationsdatabasen, line 0, x2)
```
