### ISSUE TITLE
Filtrera bort sökresultat utan licens

### ISSUE THREAD

**Issue by Ainali** [DIGGSweden/dataportal-web#3]
Som användare vill jag ha sökresultat som jag kan återanvända under någon licens, oavsett vilken, så att jag är säker på vilka villkor som gäller. Nu kan jag välja licens att filtrera på en och en, det skulle vara fint om alla kunde väljas i ett svep så att [en sökning men många träffar utan licens](https://www.dataportal.se/sv/datasets?p=1&q=regioner&s=2&t=20&f=http%3A%2F%2Fpurl.org%2Fdc%2Fterms%2Fpublisher%7C%7Chttps%3A%2F%2Fcatalog.skl.se%2Fstore%2F1%2Fresource%2F1%7C%7Cfalse%7C%7Curi%7C%7COrganisationer%7C%7CSveriges%20Kommuner%20och%20Landsting%20(SKL)&rt=dataset%24esterms_IndependentDataService%24esterms_ServedByDataService) blev lättare att navigera.

**Comment by kristineulander** [comment]
Hej Jan, ber om ursäkt för det sena svaret! 

Försöker förstå hur du menar så jag skulle vilja ställa några uppföljande frågor så att jag verkligen förstått dig rätt. 

Idag söker man i fritexten och kan i tillägg smala av sökningen för att enbart få t.ex vissa särskilda licenser t.ex CCO. I den länken du skickade är 1) sökordet "regioner" samt 2) filtrerat på att hitta data från enbart SKR. Det resulterar i 9 st träffar. När jag då tittar i licensfiltret framkommer det att SKL inte har licensierat några av dessa datamängder (eller åtminstone inte beskrivit det i sin metadata). Om de hade licensierat några av sökträffarna hade denna licens viktats upp inom filtret. 

Innan du startar sökningen kan du t.ex trycka i licensfiltret för att smala av sökningen helt för att få träffar med med bara din önskade licens. Nu är det några många olika i filtret men vi arbetar med rekommendationer för att få en ökad harmonisering av vilka licenser som används. Men jag tolkar dig som att du önskar en knapp/funktion kanske i toppen av listan för att åstadkomma samma fastän då att man automatiskt triggar en regel på "välj alla"? Tolkar jag dig rätt? 

Vi arbetar med olika typer av rekommendationer för att fler ska licensiera sin data och även beskriva det i metadatan. För att lyfta upp vikten av att sätta licenser på sin data har vi t.ex höjt upp kravnivå för publicister från "valfri" till "rekommenderad". I vissa fall använder organisationer mer specificerade avtalsvillkor och då beskriver man det i sin metadata också, men kommer det inte upp under "licens"

**Comment by Ainali** [comment]
> Men jag tolkar dig som att du önskar en knapp/funktion kanske i toppen av listan för att åstadkomma samma fastän då att man automatiskt triggar en regel på "välj alla"? Tolkar jag dig rätt?

Ja, "välj alla licenser" är det jag efterfrågar. Mitt användarfall är helt enkelt att jag ska kunna veta _hur_ jag kan återanvända den data jag hittar.

**Comment by kristineulander** [comment]
Tack för input. Vi tar med oss behovet framåt. Vänliga hälsningar /Kristine

**Comment by Ainali** [comment]
Kul att ni jobbar vidare med detta! Notera att jag bara vill välja alla licenser. Jag vill inte få med träffar som exempelvis den som visas i din mockup med "villkorOkanda" (och 584 träffar!) eftersom att det inte är en licens utan också en avsaknad av en maskinläsbar licens.

**Comment by Ainali** [comment]
Ja, jag menade absolut inte att argumentera emot förändringen, den är helt klart bra och ett steg i rätt riktning. Jag ville bara vara tydlig med att den inte löser mitt problem.

**Comment by kristineulander** [comment]
Efter att ha vändigt och vridit lite kring licensfrågan har vi nu skickat upp en produktionssättning av licensfiltret. 

Vi landade i att vi först prioritera att "rensa upp" i filtret, vilket nu är gjort. Det är därmed nu enklare att få översikt i filtret och att man därigenom också enklare kan kryssa i de licenstyper man vill filtrera på.
