### ISSUE TITLE
Update twitter/facebook link in footer

### ISSUE THREAD

**Issue by borsna** [diggsweden/dataportal-web#39]
### What benefits does the suggestion solve?

The twitter link in the footer on https://www.dataportal.se links to a inactive account

### Feature suggestion description

Link to active twitter account instead of https://twitter.com/oppnadata_psi

### Alternative solutions

Remove link

**Comment by borsna** [comment]
Same case for the facebook link:
https://www.facebook.com/oppnadata.psi/

**Comment by MickeA** [comment]
Thank you for reporting issue for dataportal.se!
We find this issue to be obsolete now after the redesign of dataportal.se has been released.
