### ISSUE TITLE
CR: Senaste ändringar

### ISSUE THREAD

**Issue by salgo60** [DIGGSweden/dataportal-web#4]
se community.dataportal.se [topic 44](https://community.dataportal.se/topic/44)

![image](https://user-images.githubusercontent.com/14206509/107679200-8d860280-6c9c-11eb-939d-afbbe23a3738.png)

**Comment by egils-consulting** [comment]
Jag önskar mig ett RSS flöde. 
Skulle vara intressant om det gick att abonnera på sökningar så jag kan filtrera bort sånt som är skräp för mig.
Om alla sökningar har ett RSS flöde då kan ni som datahamstern föreslagit bara göra en länk till en sökning på alla objekt i omvänd kronologisk ordning 😃
2 flugor i en smäll. 😉

**Comment by salgo60** [comment]
Ny feedback behövs troligen något som facebooks urval av vad jag skall se eller [GitHub Explore today](https://github.com/explore) där man anger sina intressen och sedan sker ett intelligent urval av det som man r intresserad av

**Nedan bild med dagens 1054 händelser....** som dök upp med datahamstern....

![image](https://user-images.githubusercontent.com/14206509/109975822-56cf6500-7cfb-11eb-9154-dc7af97317d9.png)

Min tro är som alltid att laddas saker upp som text strängar så ser vi inga samband utan det skall vara Länkade data så kan man pernumerera mer intelligent på nyheter
* arbetsmarknadsrelaterade
* allt med Forshaga
* allt med FNs miljämål etc....

**Comment by salgo60** [comment]
@GrumpyMan är inte detta du vill ha i [någon form](https://community.dataportal.se/topic/986/prenumerera-p%C3%A5-nya-datak%C3%A4llor)

<img width="1179" alt="image" src="https://github.com/user-attachments/assets/45ab0288-f0be-418c-a6d3-4c2bc17de736">

vet inte varför denna stängdes utan kommentar av @danfun-kit Oct 3, 2022 känns fel tänkt

* så länge datasettens kategorier eller att vi har länkade data så gissar jag att det kommer att vara problem med vildvuxna dataset
  * helst att ett [ekosystem skapas](https://github.com/salgo60/DIGG-skuggbacklog/issues/76) 

det jag tycker mig se

![image](https://github.com/user-attachments/assets/81cdc878-055e-4752-a014-780d0c55489f)
