### ISSUE TITLE
Engelskt namn på organisation i "Övrig aktör" visas på svensk landningssida

### ISSUE THREAD

**Issue by borsna** [diggsweden/dataportal-web#40]
### What happened?

När man besöker en landningssida för ett dataset på dataportal.se så visas det engelska namnet på organisationen även om ett svenskt namn finns angivet i metadatan.

### Steps To Reproduce

1. Besök dataset med organisation som har namn på svenska & engelska t.ex. https://www.dataportal.se/sv/datasets/818_3968/som-undersokningen-kommun-som-2004-tjorn
2. Namnet som visas i högerkolumnen visas på engelska på svenska sidan under "Övrig aktör"

### What did you expect?

Det svenska namnet `Göteborgs universitet, SOM-institutet`

### Optional Screenshots

![image](https://github.com/diggsweden/dataportal-web/assets/794445/01e5fdf4-615e-4783-bf79-277be93f003c)

**Comment by MickeA** [comment]
Hej, det svenska namnet visas nu som det ska. 
Stänger denna ticket. 
Tack för att du rapporterat in förbätringar!
