### ISSUE TITLE
Möjlighet att filtrera på myndighetstyp

### ISSUE THREAD

**Issue by Ainali** [diggsweden/dataportal-web#5]
Jag letade efter budgetar, och det vore fint om det gick att filtrera på myndighetstyp så att jag till exempel enkelt skulle kunna hitta alla budgetar från kommuner och så vidare.

**Comment by jonassodergren** [comment]
Är frågan omhändertagen?

**Comment by Ainali** [comment]
> Är frågan omhändertagen?

Issuen är inte assignad till någon, och den är inte omnämnd i några commits eller pull requests, så det verkar inte som det.

**Comment by TryggTorkel** [comment]
Tack för bra idé! Vi tar med oss frågan. Det kommer troligen dröja lite innan vi kan göra något åt den, men vi är på väg att börja titta på filter och sök och då tar vi med oss även detta.

**Comment by MickeA** [comment]
Hej, dataportalen.se har fått en redesign nyligen där bland annat söken med filter byggst om en del.
Är detta fortfarande något som efterfrågas?

**Comment by Ainali** [comment]
Jag skulle säga att det är löst genom att kunna filtrera på organisationstyp. Tack!
