### ISSUE TITLE
Duplicate update frequency choice

### ISSUE THREAD

**Issue by Adilius** [diggsweden/dataportal-web#7]
## Expected Behavior
When you filter `Update frequency` in `Search data` web page the expectation is one unique choice for each update frequency

## Current Behavior
Currently the `Continuous` (and `Kontinuerlig` for Swedish page) choice appears twice as shown below
![image](https://user-images.githubusercontent.com/43440295/132002810-e8ba315d-d89c-4086-b56b-5b7894ccabb1.png)

## Steps to Reproduce
1. Go to `Search data` page [Link](https://www.dataportal.se/en/datasets?q=&f=)
2. Click `Update frequency` dropdown button

## Context
Google Chrome Version 92.0.4515.159 (Official Build) (64-bit)

Currently the choice with 184 results leads to correctly represented and translated update frequency information.
![image](https://user-images.githubusercontent.com/43440295/132003430-77890ff8-1d29-4013-a727-8b32fa459aa1.png)

Picking any article from the 184 results shows the correct update frequency information.
![image](https://user-images.githubusercontent.com/43440295/132003481-fba0a071-7b9b-4d5c-a848-43a62a2b034b.png)

While the other 8 results lead to incorrectly represented update frequency.
![image](https://user-images.githubusercontent.com/43440295/132003548-b2da6c01-68c4-4a62-bad0-0b31692c46c8.png)

Possibly some faults arising from two keys with the same value in translation resources.
[English translation file](https://github.com/DIGGSweden/dataportal-web/blob/7abcc7fca5b7aaf310d1be2b2240e2968c437c40/src/translations/en/resources.json#L75#L76)
[Swedish translation file](https://github.com/DIGGSweden/dataportal-web/blob/7abcc7fca5b7aaf310d1be2b2240e2968c437c40/src/translations/sv/resources.json#L73#L74)

**Comment by salgo60** [comment]
Svarsfrekvensen här är tyvärr låg.... jag och andra har efterfrågat lite mer struktur/kvalitet från DIGG men inget svar se [Frågor om dataportal - Feedback på metadata? Kontrolleras metadata och dess kvalité?](https://community.dataportal.se/topic/155/fr%C3%A5gor-om-dataportal-feedback-p%C3%A5-metadata-kontrolleras-metadata-och-dess-kvalit%C3%A9) - känns inte som det drivs proffsigt...

**Comment by danfun-kit** [comment]
Issue created in internal backlog.

**Comment by MickeA** [comment]
Hi, Thanks for reporting an issue, 
We can not reproduce this anymore from the steps given.
